Create components
tarek102/Math-magicians pull request #3
Opened 2022-08-09 16:37 UTC by tarek102

### In this PR:

- Create Calculator.js
- Design Calculator

2022-08-09 18:18 UTC, elmar8287 requested changes
Hi, @tarek102.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Nice PR description 👍 

## Required Changes ♻️

- [ ] Check the comments under the review.

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
### Please, remember to tag me (@elmar8287) in your question so I can receive the notification 👍 
![giphy](https://user-images.githubusercontent.com/49064106/180751457-52107e57-31fd-486c-97fe-bcccf4e449af.gif)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-09 18:18 UTC, elmar8287 commented on src/App.js
> +      <Calculator />
- [ ] Please, consider that the App.js should be a class-based component, as it is required in the project.

2022-08-09 18:18 UTC, elmar8287 commented on src/components/Calculator.js
> +  return (
- [ ]  Please, consider that the Calculator.js should be a class-based component, as it is required in the project.

2022-08-10 08:20 UTC, addod19 approved these changes
### Hi @tarek102, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Great job refactoring the function components into a class based components :100: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 09:11 UTC, merged